# Generated by Django 5.2.9 on 2025-12-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.IntegerField(default=0),
        ),
    ]
